### ISSUE TITLE
Constants management

### ISSUE THREAD

**Issue by PaulTerrasi** [frc-88/SwerveLibrary#1]
How do we store all of our constants? Things like CAN Ids and PID constants. We threw together a solution using WPILib preferences at the hackathon, but the code is poorly written and there were some issues with live updating those values.

The things that we want to achieve are:
1. Make it easy to change and tune values during testing
2. Solve the problem of having a 100s of values that differ from robot to robot which would normally need to be passed in as parameters to the library

Long term, I think we are going to want to use XML or JSON so we can make complex configurations like
```
SwerveModule: frontLeft
  x-location: 10
  y-location: 10
  type: differential
  AzimuthController: SparkMax
    Motor: NEO
    GearRatio:18
...
```

But we don't have to do that yet, so we may just want to stick with WPILib preferences. The most important thing is that we get some sort of constants management system setup in our code to use for development.

**Comment by PaulTerrasi** [comment]
For the sake of time, I'm just going to make this using WPILib preferences

**Comment by nix342** [comment]
How about just using a json file and putting it in the deploy folder, especially for configuration data. I'm imagining you could have several configuration files for the different robots (#1 and #2 (and #3?)) and then just use a preference to specify what configuration to load.

I don't really like the idea of configuration data directly in preferences as it clogs up an already busy namespace and makes some things that really shouldn't change, too easy to change.

**Comment by PaulTerrasi** [comment]
Long term, I think that is 100% what we want. When we have all of this code bundled into a nice little API, we are going to need so much configuration data that a config file is going to be necessary.

But I need something to get development off the ground in the next day or 2, and I don't want to spend the time doing all that. I don't plan on putting permanent configuration data in there, just the typical stuff like PID constants and sensor offsets. The rest of the configuration can be done in individual robot projects. The big downside is that the API is going to suck, but we can clean that up later.

If you want to start work on a better system, please do. I know you weren't planning on doing much work this off-season, but I will take any help I can get.
